baseURL = "https://cyb3rh4ck.github.io/"
theme = "github-style"
title = "Cyb3rh4ck D3v L1f3"
languageCode = "es"
defaultContentLanguage = "es"

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]]
    name = "Java Core"
    url = "/javaCore/"
    weight = 1
    pre = "☕ "

  [[menu.main]]
    name = "VS Code"
    url = "/vscode/"
    weight = 2
    pre = "💻 "

  [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 3
    pre = "📝 "

[params]
  author = "Cyb3rh4ck"
  github = "Cyb3rh4ck"
  twitter = "Cyb3rh4ck"
  rss = true
  lastmod = true
  userStatusEmoji = "💻"
  avatar = "https://github.com/Cyb3rh4ck.png"
  headerIcon = "https://github.com/Cyb3rh4ck.png"
  
  description = "Bitácora de IA, Java y desarrollo ágil"
  custom_css = ["css/custom.css"]
  
  # Search
  [params.search]
    enable = true
    type = "flexsearch"

  # Navbar
  [params.navbar]
    displayTitle = true
    displayLogo = true
    [params.navbar.logo]
      path = "/images/logo.png"
      link = "/"

  # Footer
  [params.footer]
    enable = true
    displayCopyright = true
    copyright = "Cyb3rh4ck D3v L1f3 © 2025"

  # UI/UX
  [params.editURL]
    enable = true
    base = "https://github.com/Cyb3rh4ck/cyb3rh4ck.github.io/edit/main/content"

  # Social Links (Navbar icon links)
  [[params.navbar.extra]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/Cyb3rh4ck"

  [[params.navbar.extra]]
    name = "Twitter"
    icon = "x-twitter"
    url = "https://twitter.com/Cyb3rh4ck"

[params.blog]
    listDesc = true

[params.mermaid]
    enable = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]


