baseURL = "https://cyb3rh4ck.github.io/"
theme = "LoveIt"
title = "Cyb3rh4ck´s dev life"
languageCode = "en"
languageName = "English"
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true

# Pagination config
[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

# Menu config
[menu]
  [[menu.main]]
    name = "VS Code"
    url = "/vscode/"
    weight = 2
    title = "🚀 Bienvenido al módulo de **VS Code**"
    pre = "<i class='fa-solid fa-code'></i>"

  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 3
    pre = "<i class='fas fa-file-alt'></i>"

  [[menu.main]]
    weight = 4
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    title = "all posts"
    pre = "<i class='fas fa-folder-open'></i>"

[params]
  defaultTheme = "light"
  gitRepo = "https://github.com/Cyb3rh4ck/cyb3rh4ck.github.io"
  fingerprint = ""
  dateFormat = "2006-01-02"
  title = "Cyb3rh4ck D3v L1f3"
  description = "Bitácora de IA, Java y desarrollo ágil"
  images = ["/content/img/avatarCyb3r.png"]
  defaultContentLanguage = "es"
  showBreadCrumbs = true
  enableAnchorLink = true
  enableMermaid = true

  [params.author]
    name = "Cyb3rh4ck"
    email = ""
    link = ""
    avatar = "/images/avatar_02.png"

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = "/images/logo.png"
      name = "Cyb3rh4ck D3v L1f3"
      pre = ""
      post = ""
      typeit = false

  [params.social]
    GitHub = "Cyb3rh4ck"
    Linkedin = "cyb3rh4ck"
    X = "@Cyb3rh4ck"
    Facebook = "codigojava"

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/avatar_02.png"
      title = "Código, Café y Caos Controlado"
      subtitle = "Pensamientos de un desarrollador backend entre builds rotos y deploys exitosos"
      typeit = true
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 6

  [params.footer]
    enable = true
    custom = ''
    hugo = true
    copyright = true
    author = true
    since = 2025
    icp = ""
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.page]
    mermaid = true

# Markup related configuration in Hugo
[markup]
  [markup.highlight]
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
