baseURL = 'https://cyb3rh4ck.github.io/'
languageCode = 'es'
DefaultContentLanguage = "es"
hasCJKLanguage = false
title = 'Cyb3rh4ck D3v L1f3'
theme = 'github-style'
enableRobotsTXT = true
googleAnalytics = "G-E4FGN4JJGQ"

[params]
  Keywords = ["Java", "Spring Boot", "Software Architecture", "Blog", "Backend", "Desarrollo", "Cyb3rh4ck"]
  author = 'Cyb3rh4ck'
  github = 'Cyb3rh4ck'
  description = 'Café, Código y Spring Boot'
  avatar = 'https://github.com/Cyb3rh4ck.png'
  headerIcon = 'https://github.com/Cyb3rh4ck.png'
  enableGitalk = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [params.gitalk]
    clientID = "Ov23lizvEX2mDJe9frz6"
    clientSecret = "80b7996e26b5152797ef715ce13e07052cf2c826"
    repo = "cyb3rh4ck.github.io"
    owner = "Cyb3rh4ck"
    admin = "Cyb3rh4ck"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 30
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false